# Generated by Django 3.1.1 on 2020-11-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='featured',
        ),
    ]
